version: 0.2

env:
  variables:
    key: "S3_BUCKET"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands: #https://learning.getpostman.com/docs/postman/collection-runs/command-line-integration-with-newman/
      - npm install -g newman
      - yum install -y jq

  pre_build:
    commands:
      # - aws s3 cp "s3://${S3_BUCKET}/postman-env-files/PetStoreAPIEnvironment.postman_environment.json" ./02postman/
      # - aws s3 cp "s3://${S3_BUCKET}/postman-env-files/PetStoreAPI.postman_collection.json" ./02postman/
      - cd ./02postman
      - ./update-postman-env-file.sh

  build:
    commands:
      - echo Build started on `date` from dir `pwd`
      # - newman run PetStoreAPI.postman_collection.json --environment PetStoreAPIEnvironment.postman_environment.json -r cli,junit
      - newman run https://api.getpostman.com/collections/13156338-b2714324-8def-4eef-a045-483389ca05bc?apikey=PMAK-6426f350de64be2d758af4bf-43996f1058ae10083110ccd348ffdeed7d --environment https://api.getpostman.com/environments/13156338-1d0424b5-3f59-402a-b831-ce6b0446bb8f?apikey=PMAK-6426f350de64be2d758af4bf-43996f1058ae10083110ccd348ffdeed7d

reports:
  JUnitReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: '02postman/newman' # Location of the reports
